from .fastfood.formmail import FormMail
from .fastfood.msltags import MSLtags
from .fastfood.phishingbrands import PhishingBrands
from .fastfood.ddns import DDns
from .fastfood.idnhomographattack import IDNHomographAttack
from .fastfood.favicon import Favicon
from .fastfood.stringcomparison import StrComparison
from .fastfood.webshell import WebShell
from .fastfood.domainage import DomainAge
from .fastfood.dnsttl import DnsTTL
from .fastfood.fw import FW
from .fastfood.numberips import NumberIPs
from .fastfood.numbercountries import NumberCountries
from .fastfood.subdomains import Subdomains
from .fastfood.hsts import HSTS
from .fastfood.iframe import Iframe
from .fastfood.sfh import SHF
